### ISSUE TITLE
mod_syslog_v100 failed

### ISSUE THREAD

**Issue by siftuser** [CrowdStrike/automactc#1]
Noticed couple of errors - 

automactc      : ERROR    mod_syslog_v100 failed: ['Traceback (most recent call last):\n  File "automactc.py", line 299, in modExec\n    import_module(modImport)\n  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module\n    __import__(name)\n  File "/Users/user/automactc/modules/mod_syslog_v100.py", line 119, in <module>\n    module()\n  File "/Users/user/automactc/modules/mod_syslog_v100.py", line 112, in module\n    syslog_parse(c_syslog, go_syslog, headers, output)\n  File "/Users/user/automactc/modules/mod_syslog_v100.py", line 86, in syslog_parse\n    record[\'timestamp\'] = str(m.group(\'month\') + " " + m.group(\'day\') + " " + m.group(\'time\'))\nAttributeError: \'NoneType\' object has no attribute \'group\'\n']

safari         : ERROR    Module fatal error: necessary table doesn't exist in database.

Sorry, but what does the following message mean ? Thanks!
/Users/user/.ssh/authorized_keys is not a public key file.

**Comment by kshitijkumar14** [comment]
Appreciate the finds here - still working out a solution for the syslog bug, but I've updated the Safari (as well as Chrome while I was at it) and SSH modules to capture more verbose debug messages in case of errors like these.

The Safari error suggests that your version of the History.db may be an older one than the sqlite query used in the module can handle. What OS were you running against? If there's any way for you to share the DB schema, that would be helpful to write a backported query in the future. 

That SSH message is produced by the ssh-keygen tool, which indicates that the authorized_keys file doesn't contain any recognizable key data. Can you confirm that there is valid data in that file?
